name: Rust

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Version
        run: rustc --version && cargo clippy --version
      - name: Clippy
        run: cargo clippy
      - name: Format
        run: cargo fmt -- --check
      - name: Run tests
        run: cargo test --verbose
